steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build
  entrypoint: 'bash'
  args:
  - -c
  - |
    docker build -t \
      us-west1-docker.pkg.dev/$PROJECT_ID/datasetcreator-docker/datasetcreator-image:latest \
      --build-arg PROJECT_ID="$PROJECT_ID" \
      -f setup/gcp/Dockerfile \
      setup

images:
  - us-west1-docker.pkg.dev/$PROJECT_ID/datasetcreator-docker/datasetcreator-image:latest
